package com.example.domain.models.base

enum class StatusType(val value: Int) {

    OK(1),

    SERVER_NOT_INIT(100),
    SERVER_STOPPED(101),
    SERVER_TECHNICAL_WORK(102),

    BLOCKED_DEVICE(110),
    BLOCKED_USER_ACCOUNT(111),

    ERROR_UNKNOWN(120),
    ERROR_AUTHENTICATION(121),
    ERROR_TOKEN(122),
    ERROR_ACCESS(123),

    ERROR_REQUEST_METHOD(200),
    ERROR_REQUEST_NO_PARAMETER(201),
    ERROR_REQUEST_PARAMETER_TYPE(202),
    ERROR_REQUEST_PARAMETER_VALUE(203),
    ERROR_REQUEST_PARAMETER_LEN_LESS_MIN(204),
    ERROR_REQUEST_PARAMETER_LEN_MORE_MAX(205),
    ERROR_REQUEST_PROC_PARAMETER_VALUE(206),

    ERROR_FILE_NOT_FOUND(300),
    ERROR_NO_ENOUGH_MEMORY(301),
    ERROR_CREATE_FILE(302),
    ERROR_FILE_NOT_COMPLETED(303),
    ERROR_PROC_IMAGE(304),

    ERROR_ENTITY_NOT_FOUND(400),
    ERROR_VALUE_MUST_BE_UNIQUE(401),

    EXCEEDED_LIMIT_REGISTER(500),
    EXCEEDED_LIMIT_CREATE_FILE(501),
}